version: "3"

services:
  app:
    container_name: schedula_tutorial
    image: schedula/tutorial
    build:
      context: .
      target: production
      dockerfile: ./Dockerfile
    volumes:
      - ".:/code/"
    ports:
      - "3004:3000"
    environment:
      - ENVIRONMENT=DEVELOPMENT
      - NODE_ENV=DEVELOPMENT
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=postgres
      - DATABASE_DB=schedula_tutorial
      - DATABASE_PORT=5432
    depends_on:
      - postgres

  postgres:
    image: postgres:alpine
    container_name: schedula_tutorial_db
    ports:
      - "5106:5432"
    volumes:
      - ./.ignore/postgres/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=schedula_tutorial
    healthcheck:
    # Run command inside the container to check if postgres is ready AND alter DATABASE_DB
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB'"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "schedula@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "schedula123!"
    ports:
      - "16546:80"
    depends_on:
      postgres:
        condition: service_healthy